spring:
  data:
    mongodb:
      uri: mongodb://heroadmin:villain1@ds237922.mlab.com:37922/heroesvillains

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.11.11
